### ISSUE TITLE
Getting error JqUploadModule is not a constructor when using Yeoman generator

### ISSUE THREAD

**Issue by ronak90** [forms-angular/forms-angular#86]
I followed all the instruction given [here](https://www.forms-angular.org/#/get-started). I tried manual way as well as Yeoman way. I am on Windows machine. I installed all the dependencies. In Yeoman way I am getting this error.

```
D:\Projects\Forms-Angular-Demo-Yo\node_modules\forms-angular\server\data_form.js:50
        this.fileUploader = new JqUploadModule(this, processArgs, this.options.JQMongoFileUploader);
                            ^

TypeError: JqUploadModule is not a constructor
    at new DataForm (D:\Projects\Forms-Angular-Demo-Yo\node_modules\forms-angular\server\data_form.js:50:29)
    at Object.<anonymous> (D:\Projects\Forms-Angular-Demo-Yo\server\app.js:35:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

In manual way I am getting this error.

```
D:\Projects\Forms-Angular-Demo\node_modules\forms-angular\server\data_form.js:36
    app.locals.formsAngular = app.locals.formsAngular || [];
                                        ^

TypeError: Cannot read property 'formsAngular' of undefined
    at new DataForm (D:\Projects\Forms-Angular-Demo\node_modules\forms-angular\server\data_form.js:36:41)
    at Object.<anonymous> (D:\Projects\Forms-Angular-Demo\server.js:23:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

Am I missing anything?

**Comment by mchapman** [comment]
Sorry - I just changed the API - see https://github.com/forms-angular/fng-jq-upload/blob/master/CHANGELOG.md

I am intending to do a proper release 0.10.0 with the website as an exemplar, but may not get around to it today.  Can you temporarily remove server side plugins?  If so then probably a good idea for a short while.

**Comment by ronak90** [comment]
I updated the code to add plugin correctly. But now I am getting error when try to upload the file. The error is `404 Not Found Cannot POST /file/upload/Applicant`. Any changes required?

**Comment by mchapman** [comment]
I think that everything is now working fine - the [website](http://www.forms-angular.org) itself, [glitch example](https://forms-angular.glitch.me) the manual and Yeoman Generator methods of creating from the [get started page](https://www.forms-angular.org/#/get-started).

Let me know if you find I am wrong.
